#ifndef GNARLAXX_SOUNDS_H
#define GNARLAXX_SOUNDS_H
typedef enum Sound {
    SOUND_PLAYER_SHOT,
    SOUND_ENEMY_SHOT,
    SOUND_HIT,
    SOUND_EXPLOSION,
    SOUND_BOSS_EXPLOSION,
    SOUND_WARNING,
    SOUND_MENU_CONFIRM,
    SOUND_BOSS_RAM,
    SOUND_INTRO_WARNING,
    SOUND_INTRO_GO,
    SOUND_COUNT
} Sound;
#endif
