// Generated by tools/generate_odin_assets.py; edit assets/manifest.json.
package game

Sprite :: enum {
    Player_Left,
    Player_Idle,
    Player_Right,
    Player_Flame_0,
    Player_Flame_1,
    Pawn_0,
    Pawn_1,
    Drone_0,
    Drone_1,
    Drone_2,
    Player_Bullet,
    Enemy_Bullet,
    Enemy_Bullet_Hot,
    Explosion_0,
    Explosion_1,
    Explosion_2,
    Explosion_3,
    Explosion_4,
    Spark,
    Life,
    Boss_Body,
    Boss_Gun_Left,
    Boss_Gun_Right,
    Boss_Core,
    Stars_Far_0,
    Stars_Far_1,
    Stars_Far_2,
    Stars_Far_3,
    Stars_Near_0,
    Stars_Near_1,
    Stars_Near_2,
    Stars_Near_3,
    Title,
    Level_Cleared,
}

Atlas_Rect :: struct { x, y, w, h: int }
SPRITE_RECTS :: [Sprite]Atlas_Rect{
    .Player_Left = {2, 2, 32, 32},
    .Player_Idle = {38, 2, 32, 32},
    .Player_Right = {74, 2, 32, 32},
    .Player_Flame_0 = {110, 2, 32, 16},
    .Player_Flame_1 = {146, 2, 32, 16},
    .Pawn_0 = {182, 2, 32, 32},
    .Pawn_1 = {218, 2, 32, 32},
    .Drone_0 = {254, 2, 32, 32},
    .Drone_1 = {290, 2, 32, 32},
    .Drone_2 = {326, 2, 32, 32},
    .Player_Bullet = {362, 2, 8, 16},
    .Enemy_Bullet = {374, 2, 8, 8},
    .Enemy_Bullet_Hot = {386, 2, 8, 8},
    .Explosion_0 = {398, 2, 32, 32},
    .Explosion_1 = {434, 2, 32, 32},
    .Explosion_2 = {470, 2, 32, 32},
    .Explosion_3 = {2, 38, 32, 32},
    .Explosion_4 = {38, 38, 32, 32},
    .Spark = {74, 38, 32, 32},
    .Life = {110, 38, 16, 16},
    .Boss_Body = {130, 38, 96, 96},
    .Boss_Gun_Left = {230, 38, 32, 48},
    .Boss_Gun_Right = {266, 38, 32, 48},
    .Boss_Core = {302, 38, 32, 40},
    .Stars_Far_0 = {338, 38, 32, 32},
    .Stars_Far_1 = {374, 38, 32, 32},
    .Stars_Far_2 = {410, 38, 32, 32},
    .Stars_Far_3 = {446, 38, 32, 32},
    .Stars_Near_0 = {2, 138, 32, 32},
    .Stars_Near_1 = {38, 138, 32, 32},
    .Stars_Near_2 = {74, 138, 32, 32},
    .Stars_Near_3 = {110, 138, 32, 32},
    .Title = {146, 138, 264, 40},
    .Level_Cleared = {2, 182, 216, 24},
}

sprite_rect :: proc(id: Sprite) -> Atlas_Rect {
    rects := SPRITE_RECTS
    return rects[id]
}

ATLAS_WIDTH :: 512
ATLAS_HEIGHT :: 512
FONT_WIDTH :: 128
FONT_HEIGHT :: 64
FONT_CELL_WIDTH :: 8
FONT_CELL_HEIGHT :: 8
FONT_COLUMNS :: 16
FONT_FIRST_CODEPOINT :: 0
FONT_COUNT :: 128
FONT_ADVANCE :: 8
BACKGROUND_TILE_SIZE :: 32
BACKGROUND_PATTERN_ROWS :: 2
BACKGROUND_PATTERN_COLUMNS :: 2
BACKGROUND_PATTERN :: [BACKGROUND_PATTERN_ROWS][BACKGROUND_PATTERN_COLUMNS]int{{0, 1}, {2, 3}}
BOSS_LEFT_GUN_OFFSET_X :: -27
BOSS_LEFT_GUN_OFFSET_Y :: 50
BOSS_RIGHT_GUN_OFFSET_X :: 91
BOSS_RIGHT_GUN_OFFSET_Y :: 50
BOSS_CORE_OFFSET_X :: 32
BOSS_CORE_OFFSET_Y :: 26
