package game

// Same tuning as the dynamic C baseline; dimensions derive from shared asset metadata.
GAME_WIDTH :: 400
GAME_HEIGHT :: 500
HUD_HEIGHT :: 30
WINDOW_SCALE :: 2
GAME_CENTER_X :: (GAME_WIDTH * .5)
GAME_STEP :: (1.0 / 120.0)
PLAYER_LIVES :: 3
PAWN_WAVE_COUNT :: 10
PAWNS_PER_WAVE :: 5
DRONE_COUNT :: 5
FIRST_WAVE_TIME :: .5
WAVE_INTERVAL :: 4.5
FIRST_DRONE_TIME :: 7.0
DRONE_INTERVAL :: 9.0
PLAYER_SPAWN_BOTTOM_INSET :: 80.0
PLAYER_ENTRY_MARGIN :: 35.0
PLAYER_SPAWN_Y :: (GAME_HEIGHT - PLAYER_SPAWN_BOTTOM_INSET)
PLAYER_ENTRY_Y :: (GAME_HEIGHT + PLAYER_ENTRY_MARGIN)
PLAYER_HALF_WIDTH :: (f32(SPRITE_RECTS[.Player_Idle].w) * .5)
PLAYER_HALF_HEIGHT :: (f32(SPRITE_RECTS[.Player_Idle].h) * .5)
PLAYER_ACCELERATION :: 1800.0
PLAYER_DRAG :: 8.0
PLAYER_INVINCIBILITY_TIME :: 2.5
PLAYER_SHOT_SPEED :: 620.0
PLAYER_SHOT_INTERVAL :: .14
PLAYER_MUZZLE_GAP :: 2.0
PLAYER_BANK_SPEED :: 35.0
PAWN_SIDE_MARGIN :: 60.0
PAWN_SPAWN_GAP :: 12.0
PAWN_ROW_STAGGER :: 18.0
PAWN_SPEED :: 55.0
PAWN_SWAY_AMPLITUDE :: 32.0
PAWN_SWAY_RATE :: 1.6
PAWN_WAVE_PHASE :: .7
PAWN_FIRST_SHOT_DELAY :: 1.4
PAWN_SHOT_STAGGER :: .18
PAWN_SHOT_INTERVAL :: 2.7
PAWN_SHOT_SPEED :: 95.0
PAWN_MIN_SHOT_SPEED_Y :: 65.0
PAWN_SHOOT_BOTTOM_INSET :: 140.0
DRONE_LANE_COUNT :: 5
DRONE_SIDE_MARGIN :: 70.0
DRONE_SPAWN_GAP :: 8.0
DRONE_APPROACH_SPEED :: 85.0
DRONE_CHARGE_SPEED :: 260.0
DRONE_STEERING_RATE :: 3.0
DRONE_APPROACH_TIME :: 1.4
DRONE_WARNING_TIME :: .7
DRONE_CHARGE_TIME :: (DRONE_APPROACH_TIME + DRONE_WARNING_TIME)
DRONE_HOMING_TIME :: .6
DRONE_HOMING_END :: (DRONE_CHARGE_TIME + DRONE_HOMING_TIME)
DRONE_LIFETIME :: 7.0
PLAYER_HURT_RADIUS :: 10.0
ENEMY_HURT_RADIUS :: 16.0
ENEMY_CONTACT_RADIUS :: 22.0
ENEMY_CULL_MARGIN_X :: 60.0
ENEMY_CULL_MARGIN_Y :: 40.0
BULLET_CULL_MARGIN_X :: 20.0
BULLET_CULL_MARGIN_Y :: 24.0
BOSS_GUN_HP :: 10
BOSS_CORE_HP :: 10
BOSS_GUN_SHOTS :: 3
BOSS_CORE_SHOTS :: 5
BOSS_HALF_WIDTH :: (f32(SPRITE_RECTS[.Boss_Body].w) * .5)
BOSS_HALF_HEIGHT :: (f32(SPRITE_RECTS[.Boss_Body].h) * .5)
BOSS_SPAWN_GAP :: 22.0
BOSS_TOP_GAP :: 14.0
BOSS_REST_Y :: (HUD_HEIGHT + BOSS_TOP_GAP + BOSS_HALF_HEIGHT)
BOSS_ENTRY_SPEED :: 65.0
BOSS_ROAM_AMPLITUDE :: 85.0
BOSS_SWAY_RATE :: 1.2
BOSS_FIRE_DRIFT_SPEED :: 35.0
BOSS_FIRE_SIDE_MARGIN :: 95.0
BOSS_RETRACT_DISTANCE :: 35.0
BOSS_EXTEND_RATE :: 2.0
BOSS_ROAM_TIME :: .8
BOSS_WARNING_TIME :: .9
BOSS_FIRE_TIME :: 3.0
BOSS_RETRACT_TIME :: .65
BOSS_RAM_TRAVEL_TIME :: .75
BOSS_RAM_HOLD_TIME :: .25
BOSS_RETURN_TIME :: 1.5
BOSS_RAM_SIDE_MARGIN :: 65.0
BOSS_RAM_MIN_Y :: 190.0
BOSS_RAM_BOTTOM_INSET :: 80.0
BOSS_SWEEP_RATE :: 2.3
BOSS_SWEEP_ANGLE :: .55
BOSS_GUN_SHOT_ANGLE :: .28
BOSS_CORE_SHOT_ANGLE :: .24
BOSS_GUN_SHOT_SPEED :: 105.0
BOSS_CORE_SHOT_SPEED :: 125.0
BOSS_GUN_SHOT_INTERVAL :: .38
BOSS_CORE_SHOT_INTERVAL :: .18
BOSS_GUN_MUZZLE_INSET :: 2.0
BOSS_SHOT_HIT_PADDING :: 2.0
BOSS_HULL_SHOT_INSET_X :: 5.0
BOSS_HULL_SHOT_INSET_Y :: 6.0
BOSS_HULL_CONTACT_INSET_X :: 1.0
BOSS_HULL_CONTACT_INSET_Y :: 3.0
BOSS_GUN_CONTACT_RADIUS :: 25.0
BOSS_HIT_FLASH_TIME :: .10
PAWN_SCORE :: 100
DRONE_SCORE :: 250
BOSS_GUN_SCORE :: 500
VICTORY_SCORE :: 2000
SURVIVING_LIFE_SCORE :: 250
BRIEFING_FADE_TIME :: .7
BRIEFING_ENTRY_DELAY :: .3
BRIEFING_ENTRY_TIME :: 1.5
BRIEFING_WARNING_TIME :: .8
BRIEFING_GO_TIME :: 4.0
BRIEFING_END_TIME :: 6.8
BACKGROUND_SCROLL_SPEED :: 9.0
BACKGROUND_NEAR_SPEED_RATIO :: 2.7
EXPLOSION_FRAMES :: int(Sprite.Explosion_4) - int(Sprite.Explosion_0) + 1
EXPLOSION_FPS :: 10.0
EXPLOSION_DURATION :: (f32(EXPLOSION_FRAMES) / EXPLOSION_FPS)
RESULT_EXPLOSION_HOLD :: .1
