// Generated by tools/generate_zig_assets.py; edit assets/manifest.json.
pub const Sprite = enum {
    player_left,
    player_idle,
    player_right,
    player_flame_0,
    player_flame_1,
    pawn_0,
    pawn_1,
    drone_0,
    drone_1,
    drone_2,
    player_bullet,
    enemy_bullet,
    enemy_bullet_hot,
    explosion_0,
    explosion_1,
    explosion_2,
    explosion_3,
    explosion_4,
    spark,
    life,
    boss_body,
    boss_gun_left,
    boss_gun_right,
    boss_core,
    stars_far_0,
    stars_far_1,
    stars_far_2,
    stars_far_3,
    stars_near_0,
    stars_near_1,
    stars_near_2,
    stars_near_3,
    title,
    level_cleared,
};
pub const Rect = struct { x: i32, y: i32, w: i32, h: i32 };
pub const rectangles = [_]Rect{
    .{ .x = 2, .y = 2, .w = 32, .h = 32 },
    .{ .x = 38, .y = 2, .w = 32, .h = 32 },
    .{ .x = 74, .y = 2, .w = 32, .h = 32 },
    .{ .x = 110, .y = 2, .w = 32, .h = 16 },
    .{ .x = 146, .y = 2, .w = 32, .h = 16 },
    .{ .x = 182, .y = 2, .w = 32, .h = 32 },
    .{ .x = 218, .y = 2, .w = 32, .h = 32 },
    .{ .x = 254, .y = 2, .w = 32, .h = 32 },
    .{ .x = 290, .y = 2, .w = 32, .h = 32 },
    .{ .x = 326, .y = 2, .w = 32, .h = 32 },
    .{ .x = 362, .y = 2, .w = 8, .h = 16 },
    .{ .x = 374, .y = 2, .w = 8, .h = 8 },
    .{ .x = 386, .y = 2, .w = 8, .h = 8 },
    .{ .x = 398, .y = 2, .w = 32, .h = 32 },
    .{ .x = 434, .y = 2, .w = 32, .h = 32 },
    .{ .x = 470, .y = 2, .w = 32, .h = 32 },
    .{ .x = 2, .y = 38, .w = 32, .h = 32 },
    .{ .x = 38, .y = 38, .w = 32, .h = 32 },
    .{ .x = 74, .y = 38, .w = 32, .h = 32 },
    .{ .x = 110, .y = 38, .w = 16, .h = 16 },
    .{ .x = 130, .y = 38, .w = 96, .h = 96 },
    .{ .x = 230, .y = 38, .w = 32, .h = 48 },
    .{ .x = 266, .y = 38, .w = 32, .h = 48 },
    .{ .x = 302, .y = 38, .w = 32, .h = 40 },
    .{ .x = 338, .y = 38, .w = 32, .h = 32 },
    .{ .x = 374, .y = 38, .w = 32, .h = 32 },
    .{ .x = 410, .y = 38, .w = 32, .h = 32 },
    .{ .x = 446, .y = 38, .w = 32, .h = 32 },
    .{ .x = 2, .y = 138, .w = 32, .h = 32 },
    .{ .x = 38, .y = 138, .w = 32, .h = 32 },
    .{ .x = 74, .y = 138, .w = 32, .h = 32 },
    .{ .x = 110, .y = 138, .w = 32, .h = 32 },
    .{ .x = 146, .y = 138, .w = 264, .h = 40 },
    .{ .x = 2, .y = 182, .w = 216, .h = 24 },
};
pub fn rect(id: Sprite) Rect {
    return rectangles[@backingInt(id)];
}
pub const ATLAS_WIDTH = 512;
pub const ATLAS_HEIGHT = 512;
pub const FONT_WIDTH = 128;
pub const FONT_HEIGHT = 64;
pub const FONT_CELL_WIDTH = 8;
pub const FONT_CELL_HEIGHT = 8;
pub const FONT_COLUMNS = 16;
pub const FONT_FIRST_CODEPOINT = 0;
pub const FONT_COUNT = 128;
pub const FONT_ADVANCE = 8;
pub const BACKGROUND_TILE_SIZE = 32;
pub const BACKGROUND_PATTERN_ROWS = 2;
pub const BACKGROUND_PATTERN_COLUMNS = 2;
pub const BACKGROUND_PATTERN = [BACKGROUND_PATTERN_ROWS][BACKGROUND_PATTERN_COLUMNS]u8{ .{ 0, 1 }, .{ 2, 3 } };
pub const BOSS_LEFT_GUN_OFFSET_X = -27;
pub const BOSS_LEFT_GUN_OFFSET_Y = 50;
pub const BOSS_RIGHT_GUN_OFFSET_X = 91;
pub const BOSS_RIGHT_GUN_OFFSET_Y = 50;
pub const BOSS_CORE_OFFSET_X = 32;
pub const BOSS_CORE_OFFSET_Y = 26;
