#!/usr/bin/env python3
"""Generate compile-time atlas rectangles from the shared manifest (no runtime JSON)."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
manifest = json.loads((root / "assets/manifest.json").read_text())
lines = ["/* Generated by tools/generate_c_assets.py; edit assets/manifest.json. */",
         "#ifndef GNARLAXX_ASSETS_H", "#define GNARLAXX_ASSETS_H", "",
         "typedef enum Sprite {"]
for name in manifest["sprites"]:
    lines.append("    SPR_" + name.upper() + ",")
lines += ["    SPR_COUNT", "} Sprite;", "",
          "typedef struct AtlasRect { int x, y, w, h; } AtlasRect;",
          "static const AtlasRect SPRITE_RECTS[SPR_COUNT] = {"]
for name, rect in manifest["sprites"].items():
    lines.append("    [SPR_" + name.upper() + "] = {" + ", ".join(map(str, rect)) + "},")
lines += ["};", "", "#endif", ""]
(root / "implementations/c/assets.h").write_text("\n".join(lines))
