#!/usr/bin/env python3
"""Generate Odin asset geometry from the shared manifest (no runtime JSON)."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
manifest = json.loads((root / "assets/manifest.json").read_text())
lines = ["// Generated by tools/generate_odin_assets.py; edit assets/manifest.json.",
         "package game", "", "Sprite :: enum {"]
for name in manifest["sprites"]:
    lines.append("    " + name.title() + ",")
lines += ["}", "", "Atlas_Rect :: struct { x, y, w, h: int }",
          "SPRITE_RECTS :: [Sprite]Atlas_Rect{"]
for name, rect in manifest["sprites"].items():
    lines.append("    ." + name.title() + " = {" + ", ".join(map(str, rect)) + "},")
lines += ["}", "", "sprite_rect :: proc(id: Sprite) -> Atlas_Rect {", "    rects := SPRITE_RECTS", "    return rects[id]", "}", ""]
for key, values in (("ATLAS", manifest["atlas"]["size"]),
                    ("FONT", manifest["font"]["size"]),
                    ("FONT_CELL", manifest["font"]["cell"])):
    for suffix, value in zip(("WIDTH", "HEIGHT"), values):
        lines.append("{}_{} :: {}".format(key, suffix, value))
for key in ("columns", "first_codepoint", "count", "advance"):
    lines.append("FONT_{} :: {}".format(key.upper(), manifest["font"][key]))
lines += ["BACKGROUND_TILE_SIZE :: {}".format(manifest["background"]["tile_size"]),
          "BACKGROUND_PATTERN :: [2][2]int{{0, 1}, {2, 3}}"]
assert manifest["background"]["pattern"] == [[0, 1], [2, 3]]
for part in ("left_gun", "right_gun", "core"):
    for axis, value in zip(("X", "Y"), manifest["boss"][part + "_offset"]):
        lines.append("BOSS_{}_OFFSET_{} :: {}".format(part.upper(), axis, value))
(root / "implementations/odin/game/assets.odin").write_text("\n".join(lines) + "\n")
